# Generated by Django 5.1.3 on 2024-11-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
    ]
